# configs/simclr_rotation.yaml
augmentations:
  random_rotation:
    enabled: true # Enable Rotation
  # Ensure others are explicitly or implicitly disabled (by inheriting 'false' from base)
  color_jitter:
    enabled: false
  gaussian_blur:
    enabled: false
  grayscale:
    enabled: false
  random_erasing:
    enabled: false
  random_solarize:
    enabled: false