# configs/simclr_all.yaml
augmentations:
  color_jitter:
    enabled: true # Enable ColorJitter
  gaussian_blur:
    enabled: true # Enable GaussianBlur
  grayscale:
    enabled: true # Enable Grayscale