augmentations:
  random_rotation:
    enabled: true
  color_jitter:
    enabled: true
  gaussian_blur:
    enabled: false
  grayscale:
    enabled: true
  random_erasing:
    enabled: true
  random_solarize:
    enabled: true